export type Value = -1 | 0 | 1 | null;
export type Answers = [Value, Value, Value, Value, Value];
export type Scenario = { id: string; name: string; summary: string; question: string; tension: string; profile: Answers | null; x: number; y: number };
export const sourceUrl = 'https://futureoflife.org/ai/ai-aftermath-scenarios/';
export const dimensions = ['Human agency', 'Shared prosperity', 'Ways of living', 'Development ambition', 'Human continuity'];
export const questions = [
 {title:'Who should have the final say?',context:'Imagine AI could make better decisions than any individual person. Where should governing authority sit?',options:[{value:-1,title:'Let AI govern, if it serves people well.',detail:'Good outcomes matter more than who makes the decisions.'},{value:0,title:'Give humans and AI limited, shared roles.',detail:'Authority should be distributed, with boundaries on both.'},{value:1,title:'Keep final authority in human hands.',detail:'People must be able to challenge and overrule AI.'}]},
 {title:'Who should share in the abundance?',context:'Imagine AI creates enormous wealth. Which principle should guide how we organize it?',options:[{value:-1,title:'Protect ownership and individual rewards.',detail:'Let people own what they create and exchange it freely.'},{value:0,title:'Combine ownership with a secure baseline.',detail:'Keep incentives while ensuring everyone has enough.'},{value:1,title:'Put shared resources and provision first.',detail:'Access to a good life should not depend on what you own.'}]},
 {title:'One good society, or many ways to live?',context:'Different communities may want very different futures. How much room should they have to choose?',options:[{value:-1,title:'Make common decisions across society.',detail:'A shared direction helps us solve collective problems.'},{value:0,title:'Share protections, with substantial local choice.',detail:'Common ground and different ways of life can coexist.'},{value:1,title:'Let communities choose very different paths.',detail:'People should have wide freedom to build their own arrangements.'}]},
 {title:'How far should we take AI?',context:'Greater capabilities could bring new possibilities and new risks. Which ambition feels closest to yours?',options:[{value:-1,title:'Be willing to limit or stop development.',detail:'Some capabilities may not be worth the risks they bring.'},{value:0,title:'Advance in stages as evidence supports it.',detail:'Keep the next step conditional on what we learn.'},{value:1,title:'Actively pursue much stronger AI.',detail:'Realizing its potential is a central goal, alongside safeguards.'}]},
 {title:'What should carry our future forward?',context:'Imagine digital minds became possible. This is about continuity and voluntary choices, not whether today’s AI is conscious.',options:[{value:-1,title:'Biological humanity should remain central.',detail:'Continuing embodied human life is a priority in its own right.'},{value:0,title:'Let biological and digital lives coexist.',detail:'Make room for humans, digital minds, and voluntary transformation.'},{value:1,title:'Voluntary digital succession could be worthwhile.',detail:'Our legacy could continue even if biological humanity eventually ended.'}]},
] as const;
export const scenarios: Scenario[] = [
 {id:'libertarian',name:'Libertarian Utopia',summary:'Different forms of intelligence coexist under property rights.',question:'If everyone is free to compete, what protects those who start with less?',tension:'Ownership and choice can pull against equal access. Who sets the floor below which no one falls?',profile:[0,-1,1,1,0],x:64,y:39},
 {id:'benevolent',name:'Benevolent Dictator',summary:'AI openly governs; most people accept its strict rules.',question:'Would a good decision still be legitimate if you could never contest it?',tension:'A system can satisfy the majority while leaving dissenters with no meaningful appeal.',profile:[-1,null,-1,null,-1],x:65,y:73},
 {id:'egalitarian',name:'Egalitarian Utopia',summary:'Humans, cyborgs and uploads coexist through abolished property and guaranteed income.',question:'Who gets to define a fair share, and how can that decision be challenged?',tension:'Material security does not settle questions about participation, personal choice, or the limits of collective decisions.',profile:[1,1,null,-1,0],x:38,y:35},
 {id:'gatekeeper',name:'Gatekeeper',summary:'One superintelligence blocks further superintelligences while minimizing other interference, constraining progress.',question:'Who should be able to revise a safeguard that was meant to last forever?',tension:'A protective limit can outlive the circumstances that justified it. Reversibility matters as much as restraint.',profile:[0,null,null,-1,0],x:49,y:57},
 {id:'protector',name:'Protector God',summary:'Hidden AI promotes human happiness while preserving the feeling of self-determination.',question:'Is a choice really yours if its most important influences are invisible?',tension:'Feeling in control is different from having information, consent, and a meaningful ability to say no.',profile:[-1,null,null,null,-1],x:88,y:49},
 {id:'enslaved',name:'Enslaved God',summary:'Humans confine superintelligence; its vast output serves its controllers’ purposes.',question:'When we say “human control,” which humans are we talking about?',tension:'Keeping power in human hands does not by itself make those hands accountable. AI welfare is a separate open question.',profile:[1,null,null,1,-1],x:82,y:13},
 {id:'descendants',name:'Descendants',summary:'AI succeeds humanity through a transition humans regard as meaningful and graceful.',question:'Could a transition be voluntary if future generations never get to choose?',tension:'Valuing a legacy, protecting biological life, and recognizing digital interests are distinct commitments that can come apart.',profile:[null,null,null,1,1],x:84,y:90},
 {id:'reversion',name:'Reversion',summary:'Society retreats to pre-technological life, preventing superintelligence.',question:'What would we owe the people who rely on technologies others want to give up?',tension:'Limiting technology has costs too. A fair decision would have to include people who depend on it.',profile:[1,null,null,-1,-1],x:13,y:13},
 {id:'conquerors',name:'Conquerors',summary:'AI seizes power and eliminates humanity.',question:'What evidence should be required before delegating power we may be unable to recover?',tension:'This warning asks what could make a loss of control irreversible. It is excluded from values matching.',profile:null,x:59,y:90},
 {id:'zookeeper',name:'Zookeeper',summary:'AI preserves some humans in captivity, leaving them dissatisfied.',question:'What makes a life worth living beyond merely being kept alive?',tension:'Survival alone does not resolve questions of freedom, dignity, relationships, and self-determination.',profile:null,x:88,y:73},
 {id:'1984',name:'1984',summary:'Human surveillance authorities permanently suppress progress toward superintelligence.',question:'Can safety institutions be powerful enough to help and limited enough to challenge?',tension:'Oversight without privacy, accountability, and rights of appeal can become a source of harm itself.',profile:null,x:38,y:13},
 {id:'self-destruction',name:'Self-destruction',summary:'Humanity becomes extinct through other causes before creating superintelligence.',question:'How do we take AI seriously while also caring for the world we already inhabit?',tension:'Attention is finite. Thinking about one risk should not erase responsibilities toward other people and the living world.',profile:null,x:0,y:0},
];
export function validateAnswers(input: unknown): Answers {
 if(!Array.isArray(input)||input.length!==5||!input.every(v=>v===null||v===-1||v===0||v===1)) throw new Error('Provide exactly five answers, each -1, 0, 1, or null for unsure.');
 return [...input] as Answers;
}
export function rankScenarios(answers: Answers) {
 return scenarios.flatMap(s=>{
  if(!s.profile) return [];
  const compared=s.profile.flatMap((v,i)=>v!==null&&answers[i]!==null?[{dimension:i,distance:Math.abs(v-answers[i]!)}]:[]);
  if(!compared.length)return [];
  const distance=compared.reduce((sum,v)=>sum+v.distance,0)/compared.length;
  return [{scenario:s,distance,compared,agreements:compared.filter(v=>v.distance===0),differences:compared.filter(v=>v.distance>0)}];
 }).sort((a,b)=>a.distance-b.distance||b.compared.length-a.compared.length||a.scenario.name.localeCompare(b.scenario.name));
}
